language: node_js

node_js:
  - 10.15.0

services:
  - postgresql

cache:
  directories:
    - node_modules

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres

script:
  - npm ci
  - npm test

after_success:
  - npm run coverage
